[project]
name = "ableton-pal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["marvin>=3.2.2", "python-osc>=1.7.7", "tzdata>=2025.2"]

[project.scripts]
ableton-pal = "src.main:main"
